CREATE TABLE usuarios (
                          id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          email       VARCHAR(100) NOT NULL UNIQUE,
                          ativo       BOOLEAN NOT NULL DEFAULT TRUE,
                          data_desativacao TIMESTAMP
);

CREATE TABLE pacientes (
                           id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           id_usuario            BIGINT NOT NULL REFERENCES usuarios(id),
                           nome                  VARCHAR(50) NOT NULL,
                           data_nascimento       DATE,
                           tipo_sanguineo        VARCHAR(3),
                           codigo_emergencia     VARCHAR(200),
                           ficha_emergencial_ativa BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE agendamentos (
                              id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              id_paciente       BIGINT NOT NULL REFERENCES pacientes(id),
                              especialidade     VARCHAR(70) NOT NULL,
                              nome_clinica      VARCHAR(300),
                              motivo_consulta   TEXT,
                              tipo_consulta     VARCHAR(20),
                              data_agendamento  DATE NOT NULL,
                              hora_agendamento  TIME NOT NULL,
                              hora_fim          TIME,
                              status            VARCHAR(20) NOT NULL DEFAULT 'AGENDADO',
                              favorito          BOOLEAN NOT NULL DEFAULT FALSE,
                              arquivado         BOOLEAN NOT NULL DEFAULT FALSE,
                              google_event_id   VARCHAR(128)
);