CREATE TABLE enderecos (
                           id_endereco  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           cep          VARCHAR(9),
                           logradouro   VARCHAR(100),
                           numero       VARCHAR(20),
                           bairro       VARCHAR(255),
                           cidade       VARCHAR(255),
                           estado       VARCHAR(2),
                           complemento  VARCHAR(255)
);

CREATE TABLE profissionais (
                               id_profissional                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               id_endereco                         BIGINT REFERENCES enderecos(id_endereco),
                               nome_profissional                   VARCHAR(50),
                               numero_identificacao_profissional   VARCHAR(20),
                               contato                             VARCHAR(20),
                               nome_clinica                        VARCHAR(30),
                               email                               VARCHAR(50),
                               especialidade                       VARCHAR(70)
);

ALTER TABLE agendamentos ADD COLUMN id_profissional BIGINT REFERENCES profissionais(id_profissional);