-- 1. Adicionar a coluna CPF na tabela de pacientes já existente
ALTER TABLE pacientes ADD COLUMN cpf VARCHAR(14);

-- 2. Criar a tabela de alergias mapeada com a entidade
CREATE TABLE alergias (
                          id_alergia BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          id_paciente BIGINT NOT NULL,
                          tipo VARCHAR(1) NOT NULL, -- Recebe 'M' (Medicamentosa) ou 'A' (Alimentar)
                          descricao VARCHAR(50),

    -- Chave estrangeira ligando a alergia ao paciente dono dela
                          CONSTRAINT fk_alergia_paciente FOREIGN KEY (id_paciente) REFERENCES pacientes(id)
);