CREATE TABLE contatos (
                          id_contato   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          nome         VARCHAR(50),
                          parentesco   VARCHAR(50),
                          telefone     VARCHAR(20),
                          email        VARCHAR(50)
);
